name: SoftDev
services:
  mongodb:
    image: mongo:latest
    container_name: inkly
    ports:
      - "27017:27017"
    environment:
      # Use the variables defined in your .env
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: